services:

  back:
    build: ./
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: test_db
      DB_PORT: 3306
      DB_DIALECT: mysql
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"